<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 undefined">
        <div class="item" title="  [field:title/]"> <a href="[field:arcurl/]"> <img src="[field:litpic/]">
          <li>[field:pubdate function="MyDate('m-d',@me)"/]<span>[field:pubdate function="MyDate('Y',@me)"/]</span></li>
          <h4> [field:title/]</h4>
          <p> [field:description function="cn_substr(@me,120)"/]......</p>
          </a> </div>
      </div>