<a href="[field:arcurl/]">
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
        <div class="engin-frame"> <img src="[field:litpic/]">
          <div class="engin-text"> [field:title/] </div>
        </div>
        <div class="engin-xq">
          <li> [field:pubdate function="MyDate('m-d',@me)"/] <span> [field:pubdate function="MyDate('Y',@me)"/] </span> </li>
          <h4> [field:title/] </h4>
          <p> [field:description function="cn_substr(@me,100)"/] </p>
        </div>
      </div>
      </a>