<?php
$z[0]=Array("global","",434,461);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",481,513);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",599,631);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","(@me==\"\")? @me=\" class='active' \":@me=\"\";",868,959);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channelartlist","\r\n      <li class='{dede:field.currentstyle/}'> <a href=\"{dede:field name='typeurl'/}\"> {dede:field name='typename'/} </a> </li>\r\n      ",1005,1219);
$z[4][4]['typeid']="top";
$z[4][4]['currentstyle']="active";

?>